### PR TITLE
Integrated local GML 3.2 schema dependencies

### PR DESCRIPTION
**Pull request by coim32**

### CODE REVIEW

**Comment by coim32** [comment]
add dependency xsd

**Comment by coim32** [comment]
dependencies

**Comment by lgoltz** [comment]
@coim32 Thanks for your investigation!
As far as I see you added the GML 3.2 schema files and changed the imports in the existing (WCS) schemas. Is this correct?
What about the  changes in the file owcs_GetCoverage.xml? I don't see why this is related to this pull request.

**Comment by lgoltz** [comment]
Does this pull request fix #35?

**Comment by coim32** [comment]
adding gml 3.2 schemas allows to run wcs test ofline, no need to download them at every test execution.
changes to eowcs_getCoverage.xml are to fix wrong validation. if you want you can add a new pull request

**Comment by lgoltz** [comment]
Changes on owcs_GetCoverage.xml are already in the master.

**Pull request merged**
